### ISSUE TITLE
Response piping blob data doesn't work

### ISSUE THREAD

**Issue by danibix95** [danibix95/chino-nodejs#1]
**Issue**: when I try download to blob data after I uploaded it I'm not able to write blob on a file.

I've tried in different ways:
- writing directly to file `response.data` content (binary data)
- piping response stream to a writable stream without any library
- piping response stream to a writable stream with `through2` lib (see below)
- listen on any of writable stream and response event to try get something. The only one fired (once) was `pipe`

The test results always in timeout exceed because it seems that response never fire any events (overall the `end` event).

To reproduce the issue clone the repository, change branch to `dev`, install node packages and test it.

    git clone https://github.com/danibix95/chino-nodejs.git
    git checkout dev
    npm install
    ./node_modules/mocha/bin/mocha test/lib/blobsTest.js

**NOTE:** need to set up test settings file in [`test/testSetting.js`](https://github.com/danibix95/chino-nodejs/blob/dev/test/testsSettings.js#L5-L6) changing Chino ID & Key. Then go to your chino console create a repository and paste its id in `test/lib/blobsTest.js` at line [29](https://github.com/danibix95/chino-nodejs/blob/dev/test/lib/blobsTest.js#L29).

###  Blob download function ([src/blobs.js](https://github.com/danibix95/chino-nodejs/blob/dev/src/blobs.js))

    const fs = require("fs");
    const through2 = require("through2");
    const objects = require("./objects");

    download(blobId, newFileName = "") {
        function doDownload(resolve, reject) {
          this.call.getBlob(`/blobs/${blobId}`, {})
              .then((response) => {
                const fileName = newFileName ||
                                 response.header["content-disposition"].split("=")[1].trim();

                // console.log(response) => return the right response that contain binary data 

                response
                    .pipe(through2(function (chunk, enc, callback) {
                        //Here is never reched
                        console.log("Chunking")
                        this.push(chunk)
                    }))
                    // the file is created each time, but it's always empty
                    .pipe(fs.createWriteStream(fileName))
                    .on("finish", function () {
                        // As same as above we never reach this line
                        console.log("I've finish")
                        const ok = {
                          result_code: 200,
                          result: "success",
                          data : null,
                          message : null
                        };
                        resolve(new objects.Success(ok));
                    })
              })
              .catch((error) => { reject(new objects.ChinoError(error)) });
        }

        return new Promise(doDownload.bind(this));
    }

### Function used to retrieve blob data ([src/apiCall.js](https://github.com/danibix95/chino-nodejs/blob/dev/src/apiCall.js))

    const request = require("superagent");
    const binaryParser = require("superagent-binary-parser");

    getBlob(url, params = {}) {
        let makeCall = (resolve, reject) => {
          function blobResponseHandler(error, response) {
            if (error) {
              reject(response || error);
            }
            else {
              resolve(response);
            }
          }

          request
              .get(this.baseUrl + url)
              .auth(_(this).id, _(this).secret)
              .type("application/json")
              .accept("application/octet-stream")
              .query(params)
              .buffer(true)
              .parse(binaryParser)
              .end(blobResponseHandler);
        }

        return new Promise(makeCall);
    }

**Comment by brugnara** [comment]
@danibix95 the code has some mistakes IMO. The first one, is you have the getBlob returning a promise but you are using as a stream which is not.

I think you want to do this:

```
getBlob(url, params = {}) {
      return request
          .get(this.baseUrl + url)
          .auth(_(this).id, _(this).secret)
          .type("application/json")
          .accept("application/octet-stream")
          .query(params)
          .buffer(true)
          .parse(binaryParser);
}
```

and then:

```
getblob(params..).pipe(...)
```

**Comment by danibix95** [comment]
@brugnara So, when I need to pipe the response I must return it, instead of returning Promise, that when resolved will return a response object?

In the suggested way I'm able to write binary data. Thank you.

**Comment by brugnara** [comment]
@danibix95 you are welcome. 

Yes, when you are working with stream you have to assume the pipe is still current, just the opposite as callbacks or promises concept.

**Comment by danibix95** [comment]
Ok, I'll keep it in mind for next time.
